### ISSUE TITLE
1.47.1 update breaks cmd file execution in launch config

### ISSUE THREAD

**Issue by mcole-99** [microsoft/vscode-js-debug#632]
I have a fairly simple launch config, that's been working for some time, and the 1.47.1 update breaks it.  It launches babel-node, but I don't think babel has anything to do with the problem.

Here is the config from launch.json:

{
    "version": "0.1.0",
    "diagnosticLogging": true,
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via babel",
            "program": "${workspaceFolder}/src/server.js",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/babel-node",
            "envFile": "${workspaceFolder}/.env"
        }
    ],
    "trace": true
}

This worked on Code v1.46.1, and launched the debugger fine.  After the 1.47.1 update, when I try to launch using the same configuration, I get the following error:

<application directory>\node_modules\.bin\babel-node <application directory>\src\server.js
Error: spawn <application directory>/node_modules/.bin/babel-node ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)

When I add ".cmd" to the end of the executable file name, I no longer get the ENOENT, but I receive this error instead:

<application directory>\node_modules\.bin\babel-node.cmd <application directory>\src\server.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '"<user directory>/AppData/Local/Programs/Microsoft'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:824:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Process exited with code 1

When I downgrade Code to 1.46.1 the config works fine again.  I've also tried switching the direction of the slashes in the file path, and substituting "workspaceRoot" for "workspaceFolder", both of which result in the same errors.  Unfortunately no log file is produced when this error happens.

Am I missing some necessary config changes to get 1.47.1 working?

**VS Code Version:** 1.47.1

**Comment by connor4312** [comment]
You're hitting a variant of https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666. This will be fixed in the June recovery release which will be available in a few hours.

/duplicate

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
