### ISSUE TITLE
TypeError: Reflect.hasOwnMetadata is not a function

### ISSUE THREAD

**Issue by jdevries3133** [microsoft/vscode-js-debug#1577]
**Describe the bug**
I experienced `node out/src/debugServerMain.js` crashing on startup with the following error:

```
/Users/jack/repos/vscode-js-debug/node_modules/inversify/lib/annotation/decorator_utils.js:63
    if (Reflect.hasOwnMetadata(metadataKey, annotationTarget)) {
                ^

TypeError: Reflect.hasOwnMetadata is not a function
    at _tagParameterOrProperty (/Users/jack/repos/vscode-js-debug/node_modules/inversify/lib/annotation/decorator_utils.js:63:17)
    at tagParameter (/Users/jack/repos/vscode-js-debug/node_modules/inversify/lib/annotation/decorator_utils.js:36:5)
    at /Users/jack/repos/vscode-js-debug/node_modules/inversify/lib/annotation/decorator_utils.js:88:13
    at /Users/jack/repos/vscode-js-debug/node_modules/inversify/lib/annotation/inject_base.js:14:121
    at /Users/jack/repos/vscode-js-debug/out/src/common/sourceMaps/sourceMapFactory.js:12:37
    at __decorate (/Users/jack/repos/vscode-js-debug/out/src/common/sourceMaps/sourceMapFactory.js:8:95)
    at Object.<anonymous> (/Users/jack/repos/vscode-js-debug/out/src/common/sourceMaps/sourceMapFactory.js:159:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

I jumped back to an old revision and saw that the server started up normally, so I bisected back to the first commit with this issue, running the following command every step of the way to reproduce:

```bash
npm ci --legacy-peer-deps; npm run compile; node out/src/debugServerMain.js
```

In the end, the first problematic revision was:

```
commit 175d9120d25005db7a66a2a67317c8ce406a6c6f (refs/bisect/bad)
Author: Connor Peet <connor@peet.io>
Date:   Sat Jan 14 13:30:20 2023 -0800

    chore: adopt new localization pipeline (#1515)
    
    * chore: adopt new localization pipeline
    
    Fixes https://github.com/microsoft/vscode/issues/164438
    
    * update
    
    * add l10n path
    
    * update
    
    * update
    
    * fix function name
    
    * fixup
```

**VS Code Version:** n/a
