### ISSUE TITLE
After updating to 1.47.0 and getting the new javascript debugger I cannot debug my electron app with VSCODE anymore

### ISSUE THREAD

**Issue by chris-grabcad** [microsoft/vscode-js-debug#573]
**Describe the bug**
I have a configuration that will launch the main process of my electron app, when I run it I get an error like this Error: Cannot find module '"c:/Users/chris/AppData/Local/Programs/Microsoft' - note the "Microsoft" is terminated where there is a space in the path.

**To Reproduce**
This is my debug configuration - 
```json
		{
			"name": "...Start GCP Main",
			"type": "node",
			"request": "launch",
			"port": 5858,
			"protocol": "inspector",
			"sourceMaps": true,
			"sourceMapPathOverrides": {
				"gcp://bundled/*": "${workspaceRoot}/*"
			},
			"timeout": 30000,
			"runtimeArgs": [
				"--inspect-brk=5858",
				"${workspaceRoot}/desktop",
				"--remote-debugging-port=8315",
				"--disable-splash"
			],
			"windows": {
				"runtimeExecutable": "${workspaceRoot}\\desktop\\electron\\electron.exe"
			}
		}
```
workspaceRoot is C:\Users\Chris\Documents\GitHub\eagle-print (no spaces)
I can start this target perfectly well in 1.46.1 of vscode, but in 1.47.0 I get this

```
C:\Users\chris\Documents\GitHub\eagle-print\desktop\electron\electron.exe C:\Users\chris\Documents\GitHub\eagle-print/desktop --remote-debugging-port=8315 --disable-splash
internal/modules/cjs/loader.js:686
    throw err;
    ^

Error: Cannot find module '"c:/Users/chris/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Function.Module._load (internal/modules/cjs/loader.js:601:27)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:971:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:365:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:48:3)
    at internal/main/run_main_module.js:14:1
Process exited with code 1
```

The **only** thing that has changed is vscode.

**Log File**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4904449/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.47.0
**Additional context**
The only thing it should be trying to find in :/Users/chris/AppData/Local/Programs/ that matches `Microsoft` is `Microsoft VS Code`

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode/issues/102035. You have a few options:

1. Update to a newer version of Node+Electron
2. Use the [nightly debugger with the fix](https://github.com/microsoft/vscode-js-debug#nightly-extension) and set `"nodeVersionHint": 10`
3. Set `debug.javascript.usePreview: false` to use the previous debugger until the fix for this is released.

Thanks for filing an issue!

**Comment by connor4312** [comment]
@chid-grabcad can you please also confirm which version of electron you were using?

**Comment by chris-grabcad** [comment]
We're using Electron 5.0.13 and node 12.1.0

**Comment by connor4312** [comment]
Thanks -- resolution steps for this here

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
