### ISSUE TITLE
Debugger not working after update to 1.47.0

### ISSUE THREAD

**Issue by thegrandoverseer** [microsoft/vscode-js-debug#592]
After my IDE updated to version 1.47.0 my previously working debuggers don't work. I get the following error after the debugger tries to launch

```
env 'NODE_OPTIONS=--require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" ' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/var/folders/06/pd_lmssj3bz885hxc13dkt9h0000gp/T/node-cdp.31116-3.sock","deferredMode":false,"waitForDebugger":"","execPath":"/Users/mdobbins/.nvm/versions/node/v10.15.3/bin/node","onlyEntrypoint":false,"fileCallback":"/var/folders/06/pd_lmssj3bz885hxc13dkt9h0000gp/T/node-debug-callback-22c21c3c9805d035"}' /Users/mdobbins/projects/nautilus/node_modules/.bin/react-scripts test ideas.test --runInBand --no-cache --env=jsdom 
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '"/Applications/Visual'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:824:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**To Reproduce**

**Log File**

**VS Code Version:** 1.47.0

**Additional context**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4913616/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
You're hitting a version of https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666. The resolution steps in the comment will work for you (just ignore the electron part of it)

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!

**Comment by thegrandoverseer** [comment]
Awesome. Thanks for the quick reply. I had already figured out that I
needed to turn off the debugger preview, but was impressed when I received
your response so quickly.

--

Michael Dobbins
michaeldobbins1@gmail.com
480-309-6066
